[toolchain]
channel = "nightly-2021-09-19"
components = [
    "rust-src",
]
profile = "default"
targets = [
    "aarch64-apple-darwin",
    "aarch64-apple-ios",
#    "aarch64-apple-ios-macabi",
    "aarch64-apple-ios-sim",
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-apple-darwin",
    "x86_64-apple-ios",
#    "x86_64-apple-ios-macabi",
    "x86_64-linux-android",
    "x86_64-unknown-linux-gnu",
]
